# permissions for end users to view sharestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: sharestore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mccp-store-operator1
    app.kubernetes.io/part-of: mccp-store-operator1
    app.kubernetes.io/managed-by: kustomize
  name: sharestore-viewer-role
rules:
- apiGroups:
  - store.mccplatform.mthreads.com
  resources:
  - sharestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - store.mccplatform.mthreads.com
  resources:
  - sharestores/status
  verbs:
  - get
